# docker-compose up
# docker-compose run web rake db:migrate db:seed
#
version: '3.7'
services:
  db:
    image: postgres:13.1
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${APP}_dev
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    command: bundle exec rails new ${APP} --api -m template.rb
    volumes:
      - .:/opt/${APP}
    depends_on:
      - db
volumes:
  db:
    driver: local
